// Generated by CoffeeScript 1.3.3
(function() {
  var IPHONE_USER_AGENT, callback, create_new_tab, filter, open_url, opt_extraInfoSpec, process_url, show_tab;

  IPHONE_USER_AGENT = 'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25';

  callback = function(details) {
    var header, _i, _len, _ref;
    _ref = details.requestHeaders;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      header = _ref[_i];
      if (header.name === 'User-Agent') {
        header.value = IPHONE_USER_AGENT;
      }
    }
    return {
      requestHeaders: details.requestHeaders
    };
  };

  filter = {
    urls: ['<all_urls>'],
    types: ['sub_frame']
  };

  opt_extraInfoSpec = ['blocking', 'requestHeaders'];

  chrome.webRequest.onBeforeSendHeaders.addListener(callback, filter, opt_extraInfoSpec);

  create_new_tab = function(url) {
    var iframe, sec;
    sec = document.createElement('section');
    sec.className = 'tab-content';
    iframe = document.createElement('iframe');
    iframe.src = url;
    sec.appendChild(iframe);
    document.getElementById('tab-contents').appendChild(sec);
    return sec;
  };

  show_tab = function(tab_to_show) {
    var tab, _i, _len, _ref;
    _ref = document.getElementById('tab-contents').children;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tab = _ref[_i];
      if (tab !== tab_to_show) {
        tab.style.display = 'none';
      }
    }
    return tab_to_show.style.display = 'block';
  };

  process_url = function(url) {
    if (url.indexOf('http') !== 0) {
      return 'http://' + url;
    }
    return url;
  };

  open_url = function(event) {
    var url;
    url = document.getElementById('url').value;
    return show_tab(create_new_tab(process_url(url)));
  };

  document.addEventListener('DOMContentLoaded', function(event) {
    document.getElementById('open').addEventListener('click', open_url);
    return document.getElementById('url').addEventListener('keyup', function(event) {
      if (event.keyCode === 13) {
        return open_url();
      }
    });
  });

}).call(this);
